baseURL = "https://loloftf.github.io/ocho-web/"
publishDir = "docs"
relativeURLs = true
title = "OCHO"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
languageCode = "es-es"

[languages]

[languages.es]
languageName = "Español"
contentDir = "content/es"
weight = 1

[languages.pt]
languageName = "Português"
contentDir = "content/pt"
weight = 2

[[cascade]]
  type = "legal"
  [cascade._target]
    path = "**/aviso-legal.md"

[[cascade]]
  type = "legal"
  [cascade._target]
    path = "**/politica-privacidad.md"

[[cascade]]
  type = "legal"
  [cascade._target]
    path = "**/cookies.md"

[[cascade]]
  type = "legal"
  [cascade._target]
    path = "**/condiciones.md"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
